export const VIEW_OFFERS = "VIEW_OFFERS";
export const VIEW_MY_OFFERS = "VIEW_MY_OFFERS";
export const VIEW_MY_TESTS = "VIEW_MY_TESTS";
export const VIEW_MY_PROFILE = "VIEW_MY_PROFILE";
export const VIEW_MY_CALENDAR = "VIEW_MY_CALENDAR";
export const VIEW_CONNECTION = "VIEW_CONNECTION";
