export const REQUEST_CONNECTION = "REQUEST_CONNECTION";
export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS";
export const CONNECTION_REFUSED = "CONNECTION_REFUSED";
export const RECEIVE_ERROR = "RECEIVE_ERROR";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_REFUSED = "LOGOUT_REFUSED";
